name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Tidy
      run: go mod tidy

    - name: GoFish
      run: curl -fsSL https://raw.githubusercontent.com/fishworks/gofish/main/scripts/install.sh | bash
    - run: gofish init

    - name: Buffalo
      run: gofish install buffalo
    
    - name: Get Inderect Dependencies
      run: |
        go get github.com/markbates/grift/grift@v1.5.0

    - name: Build
      run: |
        GOOS=linux GOARCH=amd64 buffalo build -o bin/calc-linux
        go get github.com/markbates/grift/grift@v1.5.0
        GOOS=darwin GOARCH=amd64 buffalo build -o bin/calc-mac
        go get github.com/markbates/grift/grift@v1.5.0
        GOOS=windows GOARCH=amd64 buffalo build -o bin/calc-windows
    
    - uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: bin/

  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: build
    name: Docker Build, Tag, Push

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        push: true
        tags: go-calc-api
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        registry: docker.pkg.github.com
        repository: captv89/calc
        tag_with_sha: true
