name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Tidy
      run: go mod tidy

    - name: GoFish
      run: curl -fsSL https://raw.githubusercontent.com/fishworks/gofish/main/scripts/install.sh | bash
    - run: gofish init

    - name: Buffalo
      run: gofish install buffalo
    
    - name: Grift
      run: go get github.com/markbates/grift/grift@v1.5.0
      
    - name: Flect
      run: go get github.com/gobuffalo/flect@v0.2.2
      
    - name: Pop
      run: go get github.com/gobuffalo/pop/v5@v5.3.3

    - name: Build
      run: buffalo build
    
    - uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: bin/
